2021-06-26 22:01 INFO test_it.py:321    Not color
2021-06-26 22:05 INFO test_it.py:35    Hello unique
2021-06-26 22:05 WARNING test_it.py:150    Hello next unique
2021-06-26 22:05 ERROR help_file.py:13    ZeroDivisionError: Hello unique

    Traceback (most recent call last):
      File "c:/Users/Malac/ownCloud/Github/mylogging/tests\help_file.py", line 11, in traceback_outside
        print(10 / 0)
    ZeroDivisionError: division by zero

2021-06-26 22:05 WARNING test_it.py:170    asdasd
2021-06-26 22:05 WARNING test_it.py:171    asdasd
2021-06-26 22:05 WARNING test_it.py:182    asdasd
2021-06-26 22:05 INFO help_file.py:17    Info outside
2021-06-26 22:05 WARNING help_file.py:6    Warn outside
2021-06-26 22:05 ERROR help_file.py:13    ZeroDivisionError: Traceback outside

    Traceback (most recent call last):
      File "c:/Users/Malac/ownCloud/Github/mylogging/tests\help_file.py", line 11, in traceback_outside
        print(10 / 0)
    ZeroDivisionError: division by zero

2021-06-26 22:05 INFO test_it.py:35    Hello unique
2021-06-26 22:05 WARNING test_it.py:150    Hello next unique
2021-06-26 22:05 ERROR help_file.py:13    ZeroDivisionError: Hello unique

    Traceback (most recent call last):
      File "c:/Users/Malac/ownCloud/Github/mylogging/tests\help_file.py", line 11, in traceback_outside
        print(10 / 0)
    ZeroDivisionError: division by zero

2021-06-26 22:05 WARNING test_it.py:170    asdasd
2021-06-26 22:05 WARNING test_it.py:171    asdasd
2021-06-26 22:05 WARNING test_it.py:182    asdasd
2021-06-26 22:05 INFO help_file.py:17    Info outside
2021-06-26 22:05 WARNING help_file.py:6    Warn outside
2021-06-26 22:05 ERROR help_file.py:13    ZeroDivisionError: Traceback outside

    Traceback (most recent call last):
      File "c:/Users/Malac/ownCloud/Github/mylogging/tests\help_file.py", line 11, in traceback_outside
        print(10 / 0)
    ZeroDivisionError: division by zero

2021-06-26 22:07 INFO test_it.py:35    Hello unique
2021-06-26 22:08 INFO test_it.py:35    Hello unique
2021-06-26 22:08 INFO <string>:1    asdave
2021-06-26 22:08 INFO <string>:1    asdaveeve
2021-06-26 22:08 WARNING test_it.py:212    Test blacklist one
2021-06-26 22:08 WARNING test_it.py:217    Test blacklist two
2021-06-26 22:08 WARNING test_it.py:150    Hello next unique
2021-06-26 22:08 ERROR help_file.py:13    ZeroDivisionError: Hello unique

    Traceback (most recent call last):
      File "c:/Users/Malac/ownCloud/Github/mylogging/tests\help_file.py", line 11, in traceback_outside
        print(10 / 0)
    ZeroDivisionError: division by zero

2021-06-26 22:08 WARNING test_it.py:170    asdasd
2021-06-26 22:08 WARNING test_it.py:171    asdasd
2021-06-26 22:08 WARNING test_it.py:182    asdasd
2021-06-26 22:08 INFO help_file.py:17    Info outside
2021-06-26 22:08 WARNING help_file.py:6    Warn outside
2021-06-26 22:08 ERROR help_file.py:13    ZeroDivisionError: Traceback outside

    Traceback (most recent call last):
      File "c:/Users/Malac/ownCloud/Github/mylogging/tests\help_file.py", line 11, in traceback_outside
        print(10 / 0)
    ZeroDivisionError: division by zero

